services:
  db:
  #PostgreSQL container configuration
    image: postgres:13 #version to be installed
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weatherdb #creates a database automatically when the container starts.
    ports:
      - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
     build: . #build image of the current directory itself, without installing any image externally
     ports:
       - "8000:8000"
     depends_on:
        db:
          condition: service_healthy
volumes:
  postgres_data:


      